# Generated by Django 2.2.5 on 2019-12-02 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20191129_1150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('user_posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='shared_posts',
            field=models.ManyToManyField(related_name='shared_posts', through='main.UserPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
