# Generated by Django 2.2.5 on 2019-12-02 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20191202_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentToComment',
        ),
    ]
