# Generated by Django 2.2.5 on 2019-12-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191202_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(default=datetime.date(2019, 12, 9)),
        ),
    ]
