# Generated by Django 2.2.7 on 2019-11-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191119_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isFemale',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
