# Generated by Django 2.2.5 on 2019-11-25 15:30

from django.db import migrations, models
import django.db.models.deletion
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191121_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=utils.upload.avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='main.Department'),
            preserve_default=False,
        ),
    ]
