# Generated by Django 2.2.1 on 2019-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191016_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_head',
            field=models.BooleanField(null=True),
        ),
    ]
