# Generated by Django 2.2.5 on 2019-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191017_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
